import { Currency, Theme, CurrencyPack, Region } from './types';

export const APP_LOGO_BASE64 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAB3RJTUUH6AYEFAgD7ATgJQAABKpJREFUeNrt3dFtG0UABNBkCaQEOkhHoBOkg5wgHaQDSAdIB9IOkh0kh06QDpIOmA/YmLEPYg95vN8+74A/YX37y7sEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACY87y19XQ89e9331t79u7dX729vf2Lg/8vAADgUeP9l7en1/345bX1Vz/+LwEA4G0+3u/t315fDwAA/N0vVwAAgD1CAAAYQggAAGFIAABAChEAAAApRAAAA KQQAQAAKUQAAACkEAEAAChEAAAApBAAAAQhAAAQIYQAAACEIAABDCAAAQhAAAQIYQAAACEEAAAhCAAAQggAAEIQAACEIAABCCAAAQggAAEIQAAACEIAABDCAAAQhAAAQIYQAAACEIAABDCAAAQhAAAQIYQAAACEEAAAhCAAAQggAAEIQAACEIAABCCAAAQggAAEIQAAACEIAABDCAAAQhAAAQIYQAAACEIAABDCAAAQhAAAQIYQAAACEEAAAhCAAAQggAAEIQAACEIAABCCAAAQggAAEIQAAACEIAABDCAAAQhAAAQIYQAAACEIAABDCAAAQhAAAQIYQAAACEEAAAhCAAAQggAAEIQAACEIAABCCAAAQggAAEIQAAACEIAABDCAAAQhAAAQIYQAAACEIAABDCAAAQhAAAQIYQAAACEEAAAhCAAAQggAAEIQAACEIAABCCAAAQggAAEIQAAACEIAABDCAAAQhAAAQIYQAAACEIAABDCAAAQhAAAQIYQAAACEEAAAhCAAAQggAAEIQAACEIAABCCAADQ+P9l7em1/345bX1Vx/+/zIAAB7j8X5v/9b6epp79+5fvb29/YuD/y+N91/enp4CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgUv8A5c7TbqUuS8IAAAAASUVORK5CYII=';

export const CURRENCIES: Currency[] = [
  // Africa
  { id: 'dzd_coin', name: 'Algerian dinar', type: 'coin', imageUrl: 'https://picsum.photos/seed/dzd_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'DZ', countryName: 'Algeria' },
  { id: 'dzd_banknote', name: 'Algerian dinar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/dzd_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'DZ', countryName: 'Algeria' },
  { id: 'aoa_coin', name: 'Angolan kwanza', type: 'coin', imageUrl: 'https://picsum.photos/seed/aoa_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'AO', countryName: 'Angola' },
  { id: 'aoa_banknote', name: 'Angolan kwanza', type: 'banknote', imageUrl: 'https://picsum.photos/seed/aoa_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'AO', countryName: 'Angola' },
  { id: 'bwp_coin', name: 'Botswana pula', type: 'coin', imageUrl: 'https://picsum.photos/seed/bwp_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'BW', countryName: 'Botswana' },
  { id: 'bwp_banknote', name: 'Botswana pula', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bwp_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'BW', countryName: 'Botswana' },
  { id: 'bif_coin', name: 'Burundian franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/bif_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'BI', countryName: 'Burundi' },
  { id: 'bif_banknote', name: 'Burundian franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bif_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'BI', countryName: 'Burundi' },
  { id: 'cve_coin', name: 'Cape Verdean escudo', type: 'coin', imageUrl: 'https://picsum.photos/seed/cve_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'CV', countryName: 'Cape Verde' },
  { id: 'cve_banknote', name: 'Cape Verdean escudo', type: 'banknote', imageUrl: 'https://picsum.photos/seed/cve_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'CV', countryName: 'Cape Verde' },
  { id: 'xaf_coin', name: 'Central African CFA franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/xaf_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'CM', countryName: 'Cameroon' },
  { id: 'xaf_banknote', name: 'Central African CFA franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/xaf_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'CM', countryName: 'Cameroon' },
  { id: 'kmf_coin', name: 'Comorian franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/kmf_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'KM', countryName: 'Comoros' },
  { id: 'kmf_banknote', name: 'Comorian franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/kmf_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'KM', countryName: 'Comoros' },
  { id: 'cdf_coin', name: 'Congolese franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/cdf_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'CD', countryName: 'DR Congo' },
  { id: 'cdf_banknote', name: 'Congolese franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/cdf_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'CD', countryName: 'DR Congo' },
  { id: 'djf_coin', name: 'Djiboutian franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/djf_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'DJ', countryName: 'Djibouti' },
  { id: 'djf_banknote', name: 'Djiboutian franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/djf_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'DJ', countryName: 'Djibouti' },
  { id: 'egp_coin', name: 'Egyptian pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/egp_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'EG', countryName: 'Egypt' },
  { id: 'egp_banknote', name: 'Egyptian pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/egp_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'EG', countryName: 'Egypt' },
  { id: 'ern_coin', name: 'Eritrean nakfa', type: 'coin', imageUrl: 'https://picsum.photos/seed/ern_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'ER', countryName: 'Eritrea' },
  { id: 'ern_banknote', name: 'Eritrean nakfa', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ern_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'ER', countryName: 'Eritrea' },
  { id: 'etb_coin', name: 'Ethiopian birr', type: 'coin', imageUrl: 'https://picsum.photos/seed/etb_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'ET', countryName: 'Ethiopia' },
  { id: 'etb_banknote', name: 'Ethiopian birr', type: 'banknote', imageUrl: 'https://picsum.photos/seed/etb_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'ET', countryName: 'Ethiopia' },
  { id: 'gmd_coin', name: 'Gambian dalasi', type: 'coin', imageUrl: 'https://picsum.photos/seed/gmd_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'GM', countryName: 'Gambia' },
  { id: 'gmd_banknote', name: 'Gambian dalasi', type: 'banknote', imageUrl: 'https://picsum.photos/seed/gmd_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'GM', countryName: 'Gambia' },
  { id: 'ghs_coin', name: 'Ghanaian cedi', type: 'coin', imageUrl: 'https://picsum.photos/seed/ghs_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'GH', countryName: 'Ghana' },
  { id: 'ghs_banknote', name: 'Ghanaian cedi', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ghs_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'GH', countryName: 'Ghana' },
  { id: 'gnf_coin', name: 'Guinean franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/gnf_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'GN', countryName: 'Guinea' },
  { id: 'gnf_banknote', name: 'Guinean franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/gnf_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'GN', countryName: 'Guinea' },
  { id: 'kes_coin', name: 'Kenyan shilling', type: 'coin', imageUrl: 'https://picsum.photos/seed/kes_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'KE', countryName: 'Kenya' },
  { id: 'kes_banknote', name: 'Kenyan shilling', type: 'banknote', imageUrl: 'https://picsum.photos/seed/kes_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'KE', countryName: 'Kenya' },
  { id: 'lsl_coin', name: 'Lesotho loti', type: 'coin', imageUrl: 'https://picsum.photos/seed/lsl_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'LS', countryName: 'Lesotho' },
  { id: 'lsl_banknote', name: 'Lesotho loti', type: 'banknote', imageUrl: 'https://picsum.photos/seed/lsl_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'LS', countryName: 'Lesotho' },
  { id: 'lrd_coin', name: 'Liberian dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/lrd_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'LR', countryName: 'Liberia' },
  { id: 'lrd_banknote', name: 'Liberian dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/lrd_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'LR', countryName: 'Liberia' },
  { id: 'lyd_coin', name: 'Libyan dinar', type: 'coin', imageUrl: 'https://picsum.photos/seed/lyd_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'LY', countryName: 'Libya' },
  { id: 'lyd_banknote', name: 'Libyan dinar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/lyd_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'LY', countryName: 'Libya' },
  { id: 'mga_coin', name: 'Malagasy ariary', type: 'coin', imageUrl: 'https://picsum.photos/seed/mga_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'MG', countryName: 'Madagascar' },
  { id: 'mga_banknote', name: 'Malagasy ariary', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mga_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'MG', countryName: 'Madagascar' },
  { id: 'mwk_coin', name: 'Malawian kwacha', type: 'coin', imageUrl: 'https://picsum.photos/seed/mwk_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'MW', countryName: 'Malawi' },
  { id: 'mwk_banknote', name: 'Malawian kwacha', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mwk_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'MW', countryName: 'Malawi' },
  { id: 'mru_coin', name: 'Mauritanian ouguiya', type: 'coin', imageUrl: 'https://picsum.photos/seed/mru_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'MR', countryName: 'Mauritania' },
  { id: 'mru_banknote', name: 'Mauritanian ouguiya', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mru_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'MR', countryName: 'Mauritania' },
  { id: 'mur_coin', name: 'Mauritian rupee', type: 'coin', imageUrl: 'https://picsum.photos/seed/mur_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'MU', countryName: 'Mauritius' },
  { id: 'mur_banknote', name: 'Mauritian rupee', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mur_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'MU', countryName: 'Mauritius' },
  { id: 'mad_coin', name: 'Moroccan dirham', type: 'coin', imageUrl: 'https://picsum.photos/seed/mad_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'MA', countryName: 'Morocco' },
  { id: 'mad_banknote', name: 'Moroccan dirham', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mad_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'MA', countryName: 'Morocco' },
  { id: 'mzn_coin', name: 'Mozambican metical', type: 'coin', imageUrl: 'https://picsum.photos/seed/mzn_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'MZ', countryName: 'Mozambique' },
  { id: 'mzn_banknote', name: 'Mozambican metical', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mzn_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'MZ', countryName: 'Mozambique' },
  { id: 'nad_coin', name: 'Namibian dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/nad_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'NA', countryName: 'Namibia' },
  { id: 'nad_banknote', name: 'Namibian dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/nad_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'NA', countryName: 'Namibia' },
  { id: 'ngn_coin', name: 'Nigerian naira', type: 'coin', imageUrl: 'https://picsum.photos/seed/ngn_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'NG', countryName: 'Nigeria' },
  { id: 'ngn_banknote', name: 'Nigerian naira', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ngn_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'NG', countryName: 'Nigeria' },
  { id: 'rwf_coin', name: 'Rwandan franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/rwf_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'RW', countryName: 'Rwanda' },
  { id: 'rwf_banknote', name: 'Rwandan franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/rwf_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'RW', countryName: 'Rwanda' },
  { id: 'shp_coin', name: 'Saint Helena pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/shp_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SH', countryName: 'Saint Helena' },
  { id: 'shp_banknote', name: 'Saint Helena pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/shp_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SH', countryName: 'Saint Helena' },
  { id: 'stn_coin', name: 'São Tomé and Príncipe dobra', type: 'coin', imageUrl: 'https://picsum.photos/seed/stn_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'ST', countryName: 'São Tomé and Príncipe' },
  { id: 'stn_banknote', name: 'São Tomé and Príncipe dobra', type: 'banknote', imageUrl: 'https://picsum.photos/seed/stn_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'ST', countryName: 'São Tomé and Príncipe' },
  { id: 'scr_coin', name: 'Seychellois rupee', type: 'coin', imageUrl: 'https://picsum.photos/seed/scr_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SC', countryName: 'Seychelles' },
  { id: 'scr_banknote', name: 'Seychellois rupee', type: 'banknote', imageUrl: 'https://picsum.photos/seed/scr_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SC', countryName: 'Seychelles' },
  { id: 'sle_coin', name: 'Sierra Leonean leone', type: 'coin', imageUrl: 'https://picsum.photos/seed/sle_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SL', countryName: 'Sierra Leone' },
  { id: 'sle_banknote', name: 'Sierra Leonean leone', type: 'banknote', imageUrl: 'https://picsum.photos/seed/sle_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SL', countryName: 'Sierra Leone' },
  { id: 'sos_coin', name: 'Somali shilling', type: 'coin', imageUrl: 'https://picsum.photos/seed/sos_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SO', countryName: 'Somalia' },
  { id: 'sos_banknote', name: 'Somali shilling', type: 'banknote', imageUrl: 'https://picsum.photos/seed/sos_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SO', countryName: 'Somalia' },
  { id: 'sls_coin', name: 'Somaliland shilling', type: 'coin', imageUrl: 'https://picsum.photos/seed/sls_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SO', countryName: 'Somalia' },
  { id: 'sls_banknote', name: 'Somaliland shilling', type: 'banknote', imageUrl: 'https://picsum.photos/seed/sls_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SO', countryName: 'Somalia' },
  { id: 'zar_coin', name: 'South African rand', type: 'coin', imageUrl: 'https://picsum.photos/seed/zar_coin/600/600', region: 'Africa', popularity: 1, countryCode: 'ZA', countryName: 'South Africa' },
  { id: 'zar_banknote', name: 'South African rand', type: 'banknote', imageUrl: 'https://picsum.photos/seed/zar_banknote/800/400', region: 'Africa', popularity: 1, countryCode: 'ZA', countryName: 'South Africa' },
  { id: 'ssp_coin', name: 'South Sudanese pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/ssp_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SS', countryName: 'South Sudan' },
  { id: 'ssp_banknote', name: 'South Sudanese pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ssp_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SS', countryName: 'South Sudan' },
  { id: 'sdg_coin', name: 'Sudanese pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/sdg_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SD', countryName: 'Sudan' },
  { id: 'sdg_banknote', name: 'Sudanese pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/sdg_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SD', countryName: 'Sudan' },
  { id: 'szl_coin', name: 'Swazi lilangeni', type: 'coin', imageUrl: 'https://picsum.photos/seed/szl_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SZ', countryName: 'Eswatini' },
  { id: 'szl_banknote', name: 'Swazi lilangeni', type: 'banknote', imageUrl: 'https://picsum.photos/seed/szl_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SZ', countryName: 'Eswatini' },
  { id: 'tzs_coin', name: 'Tanzanian shilling', type: 'coin', imageUrl: 'https://picsum.photos/seed/tzs_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'TZ', countryName: 'Tanzania' },
  { id: 'tzs_banknote', name: 'Tanzanian shilling', type: 'banknote', imageUrl: 'https://picsum.photos/seed/tzs_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'TZ', countryName: 'Tanzania' },
  { id: 'tnd_coin', name: 'Tunisian dinar', type: 'coin', imageUrl: 'https://picsum.photos/seed/tnd_coin/600/600', region: 'Africa', popularity: 2, countryCode: 'TN', countryName: 'Tunisia' },
  { id: 'tnd_banknote', name: 'Tunisian dinar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/tnd_banknote/800/400', region: 'Africa', popularity: 2, countryCode: 'TN', countryName: 'Tunisia' },
  { id: 'ugx_coin', name: 'Ugandan shilling', type: 'coin', imageUrl: 'https://picsum.photos/seed/ugx_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'UG', countryName: 'Uganda' },
  { id: 'ugx_banknote', name: 'Ugandan shilling', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ugx_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'UG', countryName: 'Uganda' },
  { id: 'xof_coin', name: 'West African CFA franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/xof_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'SN', countryName: 'Senegal' },
  { id: 'xof_banknote', name: 'West African CFA franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/xof_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'SN', countryName: 'Senegal' },
  { id: 'zmw_coin', name: 'Zambian kwacha', type: 'coin', imageUrl: 'https://picsum.photos/seed/zmw_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'ZM', countryName: 'Zambia' },
  { id: 'zmw_banknote', name: 'Zambian kwacha', type: 'banknote', imageUrl: 'https://picsum.photos/seed/zmw_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'ZM', countryName: 'Zambia' },
  { id: 'zig_coin', name: 'Zimbabwe gold', type: 'coin', imageUrl: 'https://picsum.photos/seed/zig_coin/600/600', region: 'Africa', popularity: 3, countryCode: 'ZW', countryName: 'Zimbabwe' },
  { id: 'zig_banknote', name: 'Zimbabwe gold', type: 'banknote', imageUrl: 'https://picsum.photos/seed/zig_banknote/800/400', region: 'Africa', popularity: 3, countryCode: 'ZW', countryName: 'Zimbabwe' },

  // Asia
  { id: 'afn_coin', name: 'Afghan afghani', type: 'coin', imageUrl: 'https://picsum.photos/seed/afn_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'AF', countryName: 'Afghanistan' },
  { id: 'afn_banknote', name: 'Afghan afghani', type: 'banknote', imageUrl: 'https://picsum.photos/seed/afn_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'AF', countryName: 'Afghanistan' },
  { id: 'amd_coin', name: 'Armenian dram', type: 'coin', imageUrl: 'https://picsum.photos/seed/amd_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'AM', countryName: 'Armenia' },
  { id: 'amd_banknote', name: 'Armenian dram', type: 'banknote', imageUrl: 'https://picsum.photos/seed/amd_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'AM', countryName: 'Armenia' },
  { id: 'azn_coin', name: 'Azerbaijani manat', type: 'coin', imageUrl: 'https://picsum.photos/seed/azn_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'AZ', countryName: 'Azerbaijan' },
  { id: 'azn_banknote', name: 'Azerbaijani manat', type: 'banknote', imageUrl: 'https://picsum.photos/seed/azn_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'AZ', countryName: 'Azerbaijan' },
  { id: 'bhd_coin', name: 'Bahraini dinar', type: 'coin', imageUrl: 'https://picsum.photos/seed/bhd_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'BH', countryName: 'Bahrain' },
  { id: 'bhd_banknote', name: 'Bahraini dinar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bhd_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'BH', countryName: 'Bahrain' },
  { id: 'bdt_coin', name: 'Bangladeshi taka', type: 'coin', imageUrl: 'https://picsum.photos/seed/bdt_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'BD', countryName: 'Bangladesh' },
  { id: 'bdt_banknote', name: 'Bangladeshi taka', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bdt_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'BD', countryName: 'Bangladesh' },
  { id: 'btn_coin', name: 'Bhutanese ngultrum', type: 'coin', imageUrl: 'https://picsum.photos/seed/btn_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'BT', countryName: 'Bhutan' },
  { id: 'btn_banknote', name: 'Bhutanese ngultrum', type: 'banknote', imageUrl: 'https://picsum.photos/seed/btn_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'BT', countryName: 'Bhutan' },
  { id: 'bnd_coin', name: 'Brunei dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/bnd_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'BN', countryName: 'Brunei' },
  { id: 'bnd_banknote', name: 'Brunei dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bnd_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'BN', countryName: 'Brunei' },
  { id: 'mmk_coin', name: 'Burmese kyat', type: 'coin', imageUrl: 'https://picsum.photos/seed/mmk_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'MM', countryName: 'Myanmar' },
  { id: 'mmk_banknote', name: 'Burmese kyat', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mmk_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'MM', countryName: 'Myanmar' },
  { id: 'khr_coin', name: 'Cambodian riel', type: 'coin', imageUrl: 'https://picsum.photos/seed/khr_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'KH', countryName: 'Cambodia' },
  { id: 'khr_banknote', name: 'Cambodian riel', type: 'banknote', imageUrl: 'https://picsum.photos/seed/khr_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'KH', countryName: 'Cambodia' },
  { id: 'cny_coin', name: 'Renminbi', type: 'coin', imageUrl: 'https://picsum.photos/seed/cny_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'CN', countryName: 'China' },
  { id: 'cny_banknote', name: 'Renminbi', type: 'banknote', imageUrl: 'https://picsum.photos/seed/cny_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'CN', countryName: 'China' },
  { id: 'gel_coin', name: 'Georgian lari', type: 'coin', imageUrl: 'https://picsum.photos/seed/gel_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'GE', countryName: 'Georgia' },
  { id: 'gel_banknote', name: 'Georgian lari', type: 'banknote', imageUrl: 'https://picsum.photos/seed/gel_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'GE', countryName: 'Georgia' },
  { id: 'hkd_coin', name: 'Hong Kong dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/hkd_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'HK', countryName: 'Hong Kong' },
  { id: 'hkd_banknote', name: 'Hong Kong dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/hkd_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'HK', countryName: 'Hong Kong' },
  { id: 'inr_coin', name: 'Indian rupee', type: 'coin', imageUrl: 'https://picsum.photos/seed/inr_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'IN', countryName: 'India' },
  { id: 'inr_banknote', name: 'Indian rupee', type: 'banknote', imageUrl: 'https://picsum.photos/seed/inr_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'IN', countryName: 'India' },
  { id: 'idr_coin', name: 'Indonesian rupiah', type: 'coin', imageUrl: 'https://picsum.photos/seed/idr_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'ID', countryName: 'Indonesia' },
  { id: 'idr_banknote', name: 'Indonesian rupiah', type: 'banknote', imageUrl: 'https://picsum.photos/seed/idr_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'ID', countryName: 'Indonesia' },
  { id: 'irr_coin', name: 'Iranian rial', type: 'coin', imageUrl: 'https://picsum.photos/seed/irr_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'IR', countryName: 'Iran' },
  { id: 'irr_banknote', name: 'Iranian rial', type: 'banknote', imageUrl: 'https://picsum.photos/seed/irr_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'IR', countryName: 'Iran' },
  { id: 'iqd_coin', name: 'Iraqi dinar', type: 'coin', imageUrl: 'https://picsum.photos/seed/iqd_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'IQ', countryName: 'Iraq' },
  { id: 'iqd_banknote', name: 'Iraqi dinar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/iqd_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'IQ', countryName: 'Iraq' },
  { id: 'ils_coin', name: 'Israeli new shekel', type: 'coin', imageUrl: 'https://picsum.photos/seed/ils_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'IL', countryName: 'Israel' },
  { id: 'ils_banknote', name: 'Israeli new shekel', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ils_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'IL', countryName: 'Israel' },
  { id: 'jpy_coin', name: 'Japanese yen', type: 'coin', imageUrl: 'https://picsum.photos/seed/jpy_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'JP', countryName: 'Japan' },
  { id: 'jpy_banknote', name: 'Japanese yen', type: 'banknote', imageUrl: 'https://picsum.photos/seed/jpy_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'JP', countryName: 'Japan' },
  { id: 'jod_coin', name: 'Jordanian dinar', type: 'coin', imageUrl: 'https://picsum.photos/seed/jod_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'JO', countryName: 'Jordan' },
  { id: 'jod_banknote', name: 'Jordanian dinar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/jod_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'JO', countryName: 'Jordan' },
  { id: 'kzt_coin', name: 'Kazakhstani tenge', type: 'coin', imageUrl: 'https://picsum.photos/seed/kzt_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'KZ', countryName: 'Kazakhstan' },
  { id: 'kzt_banknote', name: 'Kazakhstani tenge', type: 'banknote', imageUrl: 'https://picsum.photos/seed/kzt_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'KZ', countryName: 'Kazakhstan' },
  { id: 'kwd_coin', name: 'Kuwaiti dinar', type: 'coin', imageUrl: 'https://picsum.photos/seed/kwd_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'KW', countryName: 'Kuwait' },
  { id: 'kwd_banknote', name: 'Kuwaiti dinar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/kwd_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'KW', countryName: 'Kuwait' },
  { id: 'kgs_coin', name: 'Kyrgyz som', type: 'coin', imageUrl: 'https://picsum.photos/seed/kgs_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'KG', countryName: 'Kyrgyzstan' },
  { id: 'kgs_banknote', name: 'Kyrgyz som', type: 'banknote', imageUrl: 'https://picsum.photos/seed/kgs_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'KG', countryName: 'Kyrgyzstan' },
  { id: 'lak_coin', name: 'Lao kip', type: 'coin', imageUrl: 'https://picsum.photos/seed/lak_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'LA', countryName: 'Laos' },
  { id: 'lak_banknote', name: 'Lao kip', type: 'banknote', imageUrl: 'https://picsum.photos/seed/lak_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'LA', countryName: 'Laos' },
  { id: 'lbp_coin', name: 'Lebanese pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/lbp_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'LB', countryName: 'Lebanon' },
  { id: 'lbp_banknote', name: 'Lebanese pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/lbp_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'LB', countryName: 'Lebanon' },
  { id: 'mop_coin', name: 'Macanese pataca', type: 'coin', imageUrl: 'https://picsum.photos/seed/mop_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'MO', countryName: 'Macau' },
  { id: 'mop_banknote', name: 'Macanese pataca', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mop_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'MO', countryName: 'Macau' },
  { id: 'myr_coin', name: 'Malaysian ringgit', type: 'coin', imageUrl: 'https://picsum.photos/seed/myr_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'myr_banknote', name: 'Malaysian ringgit', type: 'banknote', imageUrl: 'https://picsum.photos/seed/myr_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'mvr_coin', name: 'Maldivian rufiyaa', type: 'coin', imageUrl: 'https://picsum.photos/seed/mvr_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'MV', countryName: 'Maldives' },
  { id: 'mvr_banknote', name: 'Maldivian rufiyaa', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mvr_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'MV', countryName: 'Maldives' },
  { id: 'mnt_coin', name: 'Mongolian tögrög', type: 'coin', imageUrl: 'https://picsum.photos/seed/mnt_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'MN', countryName: 'Mongolia' },
  { id: 'mnt_banknote', name: 'Mongolian tögrög', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mnt_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'MN', countryName: 'Mongolia' },
  { id: 'npr_coin', name: 'Nepalese rupee', type: 'coin', imageUrl: 'https://picsum.photos/seed/npr_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'NP', countryName: 'Nepal' },
  { id: 'npr_banknote', name: 'Nepalese rupee', type: 'banknote', imageUrl: 'https://picsum.photos/seed/npr_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'NP', countryName: 'Nepal' },
  { id: 'twd_coin', name: 'New Taiwan dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/twd_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'TW', countryName: 'Taiwan' },
  { id: 'twd_banknote', name: 'New Taiwan dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/twd_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'TW', countryName: 'Taiwan' },
  { id: 'kpw_coin', name: 'North Korean won', type: 'coin', imageUrl: 'https://picsum.photos/seed/kpw_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'KP', countryName: 'North Korea' },
  { id: 'kpw_banknote', name: 'North Korean won', type: 'banknote', imageUrl: 'https://picsum.photos/seed/kpw_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'KP', countryName: 'North Korea' },
  { id: 'omr_coin', name: 'Omani rial', type: 'coin', imageUrl: 'https://picsum.photos/seed/omr_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'OM', countryName: 'Oman' },
  { id: 'omr_banknote', name: 'Omani rial', type: 'banknote', imageUrl: 'https://picsum.photos/seed/omr_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'OM', countryName: 'Oman' },
  { id: 'pkr_coin', name: 'Pakistani rupee', type: 'coin', imageUrl: 'https://picsum.photos/seed/pkr_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'PK', countryName: 'Pakistan' },
  { id: 'pkr_banknote', name: 'Pakistani rupee', type: 'banknote', imageUrl: 'https://picsum.photos/seed/pkr_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'PK', countryName: 'Pakistan' },
  { id: 'php_coin', name: 'Philippine peso', type: 'coin', imageUrl: 'https://picsum.photos/seed/php_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'PH', countryName: 'Philippines' },
  { id: 'php_banknote', name: 'Philippine peso', type: 'banknote', imageUrl: 'https://picsum.photos/seed/php_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'PH', countryName: 'Philippines' },
  { id: 'qar_coin', name: 'Qatari riyal', type: 'coin', imageUrl: 'https://picsum.photos/seed/qar_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'QA', countryName: 'Qatar' },
  { id: 'qar_banknote', name: 'Qatari riyal', type: 'banknote', imageUrl: 'https://picsum.photos/seed/qar_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'QA', countryName: 'Qatar' },
  { id: 'sar_coin', name: 'Saudi riyal', type: 'coin', imageUrl: 'https://picsum.photos/seed/sar_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'SA', countryName: 'Saudi Arabia' },
  { id: 'sar_banknote', name: 'Saudi riyal', type: 'banknote', imageUrl: 'https://picsum.photos/seed/sar_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'SA', countryName: 'Saudi Arabia' },
  { id: 'sgd_coin', name: 'Singapore dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/sgd_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'SG', countryName: 'Singapore' },
  { id: 'sgd_banknote', name: 'Singapore dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/sgd_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'SG', countryName: 'Singapore' },
  { id: 'krw_coin', name: 'South Korean won', type: 'coin', imageUrl: 'https://picsum.photos/seed/krw_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'KR', countryName: 'South Korea' },
  { id: 'krw_banknote', name: 'South Korean won', type: 'banknote', imageUrl: 'https://picsum.photos/seed/krw_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'KR', countryName: 'South Korea' },
  { id: 'lkr_coin', name: 'Sri Lankan rupee', type: 'coin', imageUrl: 'https://picsum.photos/seed/lkr_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'LK', countryName: 'Sri Lanka' },
  { id: 'lkr_banknote', name: 'Sri Lankan rupee', type: 'banknote', imageUrl: 'https://picsum.photos/seed/lkr_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'LK', countryName: 'Sri Lanka' },
  { id: 'syp_coin', name: 'Syrian pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/syp_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'SY', countryName: 'Syria' },
  { id: 'syp_banknote', name: 'Syrian pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/syp_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'SY', countryName: 'Syria' },
  { id: 'tjs_coin', name: 'Tajikistani somoni', type: 'coin', imageUrl: 'https://picsum.photos/seed/tjs_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'TJ', countryName: 'Tajikistan' },
  { id: 'tjs_banknote', name: 'Tajikistani somoni', type: 'banknote', imageUrl: 'https://picsum.photos/seed/tjs_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'TJ', countryName: 'Tajikistan' },
  { id: 'thb_coin', name: 'Thai baht', type: 'coin', imageUrl: 'https://picsum.photos/seed/thb_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'TH', countryName: 'Thailand' },
  { id: 'thb_banknote', name: 'Thai baht', type: 'banknote', imageUrl: 'https://picsum.photos/seed/thb_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'TH', countryName: 'Thailand' },
  { id: 'try_coin', name: 'Turkish lira', type: 'coin', imageUrl: 'https://picsum.photos/seed/try_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'TR', countryName: 'Turkey' },
  { id: 'try_banknote', name: 'Turkish lira', type: 'banknote', imageUrl: 'https://picsum.photos/seed/try_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'TR', countryName: 'Turkey' },
  { id: 'tmt_coin', name: 'Turkmenistani manat', type: 'coin', imageUrl: 'https://picsum.photos/seed/tmt_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'TM', countryName: 'Turkmenistan' },
  { id: 'tmt_banknote', name: 'Turkmenistani manat', type: 'banknote', imageUrl: 'https://picsum.photos/seed/tmt_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'TM', countryName: 'Turkmenistan' },
  { id: 'aed_coin', name: 'United Arab Emirates dirham', type: 'coin', imageUrl: 'https://picsum.photos/seed/aed_coin/600/600', region: 'Asia', popularity: 1, countryCode: 'AE', countryName: 'United Arab Emirates' },
  { id: 'aed_banknote', name: 'United Arab Emirates dirham', type: 'banknote', imageUrl: 'https://picsum.photos/seed/aed_banknote/800/400', region: 'Asia', popularity: 1, countryCode: 'AE', countryName: 'United Arab Emirates' },
  { id: 'uzs_coin', name: 'Uzbekistani sum', type: 'coin', imageUrl: 'https://picsum.photos/seed/uzs_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'UZ', countryName: 'Uzbekistan' },
  { id: 'uzs_banknote', name: 'Uzbekistani sum', type: 'banknote', imageUrl: 'https://picsum.photos/seed/uzs_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'UZ', countryName: 'Uzbekistan' },
  { id: 'vnd_coin', name: 'Vietnamese đồng', type: 'coin', imageUrl: 'https://picsum.photos/seed/vnd_coin/600/600', region: 'Asia', popularity: 2, countryCode: 'VN', countryName: 'Vietnam' },
  { id: 'vnd_banknote', name: 'Vietnamese đồng', type: 'banknote', imageUrl: 'https://picsum.photos/seed/vnd_banknote/800/400', region: 'Asia', popularity: 2, countryCode: 'VN', countryName: 'Vietnam' },
  { id: 'yer_coin', name: 'Yemeni rial', type: 'coin', imageUrl: 'https://picsum.photos/seed/yer_coin/600/600', region: 'Asia', popularity: 3, countryCode: 'YE', countryName: 'Yemen' },
  { id: 'yer_banknote', name: 'Yemeni rial', type: 'banknote', imageUrl: 'https://picsum.photos/seed/yer_banknote/800/400', region: 'Asia', popularity: 3, countryCode: 'YE', countryName: 'Yemen' },

  // Europe
  { id: 'all_coin', name: 'Albanian lek', type: 'coin', imageUrl: 'https://picsum.photos/seed/all_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'AL', countryName: 'Albania' },
  { id: 'all_banknote', name: 'Albanian lek', type: 'banknote', imageUrl: 'https://picsum.photos/seed/all_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'AL', countryName: 'Albania' },
  { id: 'byn_coin', name: 'Belarusian ruble', type: 'coin', imageUrl: 'https://picsum.photos/seed/byn_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'BY', countryName: 'Belarus' },
  { id: 'byn_banknote', name: 'Belarusian ruble', type: 'banknote', imageUrl: 'https://picsum.photos/seed/byn_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'BY', countryName: 'Belarus' },
  { id: 'bam_coin', name: 'Bosnia and Herzegovina convertible mark', type: 'coin', imageUrl: 'https://picsum.photos/seed/bam_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'BA', countryName: 'Bosnia and Herzegovina' },
  { id: 'bam_banknote', name: 'Bosnia and Herzegovina convertible mark', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bam_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'BA', countryName: 'Bosnia and Herzegovina' },
  { id: 'bgn_coin', name: 'Bulgarian lev', type: 'coin', imageUrl: 'https://picsum.photos/seed/bgn_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'BG', countryName: 'Bulgaria' },
  { id: 'bgn_banknote', name: 'Bulgarian lev', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bgn_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'BG', countryName: 'Bulgaria' },
  { id: 'czk_coin', name: 'Czech koruna', type: 'coin', imageUrl: 'https://picsum.photos/seed/czk_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'CZ', countryName: 'Czech Republic' },
  { id: 'czk_banknote', name: 'Czech koruna', type: 'banknote', imageUrl: 'https://picsum.photos/seed/czk_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'CZ', countryName: 'Czech Republic' },
  { id: 'dkk_coin', name: 'Danish krone', type: 'coin', imageUrl: 'https://picsum.photos/seed/dkk_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'DK', countryName: 'Denmark' },
  { id: 'dkk_banknote', name: 'Danish krone', type: 'banknote', imageUrl: 'https://picsum.photos/seed/dkk_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'DK', countryName: 'Denmark' },
  { id: 'eur_coin', name: 'Euro', type: 'coin', imageUrl: 'https://picsum.photos/seed/eur_coin/600/600', region: 'Europe', popularity: 1, countryCode: 'DE', countryName: 'Germany' },
  { id: 'eur_banknote', name: 'Euro', type: 'banknote', imageUrl: 'https://picsum.photos/seed/eur_banknote/800/400', region: 'Europe', popularity: 1, countryCode: 'DE', countryName: 'Germany' },
  { id: 'gip_coin', name: 'Gibraltar pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/gip_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'GI', countryName: 'Gibraltar' },
  { id: 'gip_banknote', name: 'Gibraltar pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/gip_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'GI', countryName: 'Gibraltar' },
  { id: 'ggp_coin', name: 'Guernsey pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/ggp_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'GG', countryName: 'Guernsey' },
  { id: 'ggp_banknote', name: 'Guernsey pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ggp_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'GG', countryName: 'Guernsey' },
  { id: 'huf_coin', name: 'Hungarian forint', type: 'coin', imageUrl: 'https://picsum.photos/seed/huf_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'HU', countryName: 'Hungary' },
  { id: 'huf_banknote', name: 'Hungarian forint', type: 'banknote', imageUrl: 'https://picsum.photos/seed/huf_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'HU', countryName: 'Hungary' },
  { id: 'isk_coin', name: 'Icelandic króna', type: 'coin', imageUrl: 'https://picsum.photos/seed/isk_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'IS', countryName: 'Iceland' },
  { id: 'isk_banknote', name: 'Icelandic króna', type: 'banknote', imageUrl: 'https://picsum.photos/seed/isk_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'IS', countryName: 'Iceland' },
  { id: 'jep_coin', name: 'Jersey pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/jep_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'JE', countryName: 'Jersey' },
  { id: 'jep_banknote', name: 'Jersey pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/jep_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'JE', countryName: 'Jersey' },
  { id: 'mkd_coin', name: 'Macedonian denar', type: 'coin', imageUrl: 'https://picsum.photos/seed/mkd_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'MK', countryName: 'North Macedonia' },
  { id: 'mkd_banknote', name: 'Macedonian denar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mkd_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'MK', countryName: 'North Macedonia' },
  { id: 'imp_coin', name: 'Manx pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/imp_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'IM', countryName: 'Isle of Man' },
  { id: 'imp_banknote', name: 'Manx pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/imp_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'IM', countryName: 'Isle of Man' },
  { id: 'mdl_coin', name: 'Moldovan leu', type: 'coin', imageUrl: 'https://picsum.photos/seed/mdl_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'MD', countryName: 'Moldova' },
  { id: 'mdl_banknote', name: 'Moldovan leu', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mdl_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'MD', countryName: 'Moldova' },
  { id: 'nok_coin', name: 'Norwegian krone', type: 'coin', imageUrl: 'https://picsum.photos/seed/nok_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'NO', countryName: 'Norway' },
  { id: 'nok_banknote', name: 'Norwegian krone', type: 'banknote', imageUrl: 'https://picsum.photos/seed/nok_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'NO', countryName: 'Norway' },
  { id: 'pln_coin', name: 'Polish złoty', type: 'coin', imageUrl: 'https://picsum.photos/seed/pln_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'PL', countryName: 'Poland' },
  { id: 'pln_banknote', name: 'Polish złoty', type: 'banknote', imageUrl: 'https://picsum.photos/seed/pln_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'PL', countryName: 'Poland' },
  { id: 'ron_coin', name: 'Romanian leu', type: 'coin', imageUrl: 'https://picsum.photos/seed/ron_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'RO', countryName: 'Romania' },
  { id: 'ron_banknote', name: 'Romanian leu', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ron_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'RO', countryName: 'Romania' },
  { id: 'rub_coin', name: 'Russian ruble', type: 'coin', imageUrl: 'https://picsum.photos/seed/rub_coin/600/600', region: 'Europe', popularity: 1, countryCode: 'RU', countryName: 'Russia' },
  { id: 'rub_banknote', name: 'Russian ruble', type: 'banknote', imageUrl: 'https://picsum.photos/seed/rub_banknote/800/400', region: 'Europe', popularity: 1, countryCode: 'RU', countryName: 'Russia' },
  { id: 'rsd_coin', name: 'Serbian dinar', type: 'coin', imageUrl: 'https://picsum.photos/seed/rsd_coin/600/600', region: 'Europe', popularity: 3, countryCode: 'RS', countryName: 'Serbia' },
  { id: 'rsd_banknote', name: 'Serbian dinar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/rsd_banknote/800/400', region: 'Europe', popularity: 3, countryCode: 'RS', countryName: 'Serbia' },
  { id: 'gbp_coin', name: 'Sterling', type: 'coin', imageUrl: 'https://picsum.photos/seed/gbp_coin/600/600', region: 'Europe', popularity: 1, countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'gbp_banknote', name: 'Sterling', type: 'banknote', imageUrl: 'https://picsum.photos/seed/gbp_banknote/800/400', region: 'Europe', popularity: 1, countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'sek_coin', name: 'Swedish krona', type: 'coin', imageUrl: 'https://picsum.photos/seed/sek_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'SE', countryName: 'Sweden' },
  { id: 'sek_banknote', name: 'Swedish krona', type: 'banknote', imageUrl: 'https://picsum.photos/seed/sek_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'SE', countryName: 'Sweden' },
  { id: 'chf_coin', name: 'Swiss franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/chf_coin/600/600', region: 'Europe', popularity: 1, countryCode: 'CH', countryName: 'Switzerland' },
  { id: 'chf_banknote', name: 'Swiss franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/chf_banknote/800/400', region: 'Europe', popularity: 1, countryCode: 'CH', countryName: 'Switzerland' },
  { id: 'uah_coin', name: 'Ukrainian hryvnia', type: 'coin', imageUrl: 'https://picsum.photos/seed/uah_coin/600/600', region: 'Europe', popularity: 2, countryCode: 'UA', countryName: 'Ukraine' },
  { id: 'uah_banknote', name: 'Ukrainian hryvnia', type: 'banknote', imageUrl: 'https://picsum.photos/seed/uah_banknote/800/400', region: 'Europe', popularity: 2, countryCode: 'UA', countryName: 'Ukraine' },

  // North America
  { id: 'awg_coin', name: 'Aruban florin', type: 'coin', imageUrl: 'https://picsum.photos/seed/awg_coin/600/600', region: 'North America', popularity: 3, countryCode: 'AW', countryName: 'Aruba' },
  { id: 'awg_banknote', name: 'Aruban florin', type: 'banknote', imageUrl: 'https://picsum.photos/seed/awg_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'AW', countryName: 'Aruba' },
  { id: 'bsd_coin', name: 'Bahamian dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/bsd_coin/600/600', region: 'North America', popularity: 3, countryCode: 'BS', countryName: 'Bahamas' },
  { id: 'bsd_banknote', name: 'Bahamian dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bsd_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'BS', countryName: 'Bahamas' },
  { id: 'bbd_coin', name: 'Barbadian dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/bbd_coin/600/600', region: 'North America', popularity: 3, countryCode: 'BB', countryName: 'Barbados' },
  { id: 'bbd_banknote', name: 'Barbadian dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bbd_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'BB', countryName: 'Barbados' },
  { id: 'bzd_coin', name: 'Belize dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/bzd_coin/600/600', region: 'North America', popularity: 3, countryCode: 'BZ', countryName: 'Belize' },
  { id: 'bzd_banknote', name: 'Belize dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bzd_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'BZ', countryName: 'Belize' },
  { id: 'bmd_coin', name: 'Bermudian dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/bmd_coin/600/600', region: 'North America', popularity: 3, countryCode: 'BM', countryName: 'Bermuda' },
  { id: 'bmd_banknote', name: 'Bermudian dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bmd_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'BM', countryName: 'Bermuda' },
  { id: 'cad_coin', name: 'Canadian dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/cad_coin/600/600', region: 'North America', popularity: 1, countryCode: 'CA', countryName: 'Canada' },
  { id: 'cad_banknote', name: 'Canadian dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/cad_banknote/800/400', region: 'North America', popularity: 1, countryCode: 'CA', countryName: 'Canada' },
  { id: 'kyd_coin', name: 'Cayman Islands dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/kyd_coin/600/600', region: 'North America', popularity: 3, countryCode: 'KY', countryName: 'Cayman Islands' },
  { id: 'kyd_banknote', name: 'Cayman Islands dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/kyd_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'KY', countryName: 'Cayman Islands' },
  { id: 'crc_coin', name: 'Costa Rican colón', type: 'coin', imageUrl: 'https://picsum.photos/seed/crc_coin/600/600', region: 'North America', popularity: 2, countryCode: 'CR', countryName: 'Costa Rica' },
  { id: 'crc_banknote', name: 'Costa Rican colón', type: 'banknote', imageUrl: 'https://picsum.photos/seed/crc_banknote/800/400', region: 'North America', popularity: 2, countryCode: 'CR', countryName: 'Costa Rica' },
  { id: 'cup_coin', name: 'Cuban peso', type: 'coin', imageUrl: 'https://picsum.photos/seed/cup_coin/600/600', region: 'North America', popularity: 2, countryCode: 'CU', countryName: 'Cuba' },
  { id: 'cup_banknote', name: 'Cuban peso', type: 'banknote', imageUrl: 'https://picsum.photos/seed/cup_banknote/800/400', region: 'North America', popularity: 2, countryCode: 'CU', countryName: 'Cuba' },
  { id: 'dop_coin', name: 'Dominican peso', type: 'coin', imageUrl: 'https://picsum.photos/seed/dop_coin/600/600', region: 'North America', popularity: 2, countryCode: 'DO', countryName: 'Dominican Republic' },
  { id: 'dop_banknote', name: 'Dominican peso', type: 'banknote', imageUrl: 'https://picsum.photos/seed/dop_banknote/800/400', region: 'North America', popularity: 2, countryCode: 'DO', countryName: 'Dominican Republic' },
  { id: 'xcd_coin', name: 'Eastern Caribbean dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/xcd_coin/600/600', region: 'North America', popularity: 3, countryCode: 'LC', countryName: 'Saint Lucia' },
  { id: 'xcd_banknote', name: 'Eastern Caribbean dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/xcd_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'LC', countryName: 'Saint Lucia' },
  { id: 'gtq_coin', name: 'Guatemalan quetzal', type: 'coin', imageUrl: 'https://picsum.photos/seed/gtq_coin/600/600', region: 'North America', popularity: 3, countryCode: 'GT', countryName: 'Guatemala' },
  { id: 'gtq_banknote', name: 'Guatemalan quetzal', type: 'banknote', imageUrl: 'https://picsum.photos/seed/gtq_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'GT', countryName: 'Guatemala' },
  { id: 'htg_coin', name: 'Haitian gourde', type: 'coin', imageUrl: 'https://picsum.photos/seed/htg_coin/600/600', region: 'North America', popularity: 3, countryCode: 'HT', countryName: 'Haiti' },
  { id: 'htg_banknote', name: 'Haitian gourde', type: 'banknote', imageUrl: 'https://picsum.photos/seed/htg_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'HT', countryName: 'Haiti' },
  { id: 'hnl_coin', name: 'Honduran lempira', type: 'coin', imageUrl: 'https://picsum.photos/seed/hnl_coin/600/600', region: 'North America', popularity: 3, countryCode: 'HN', countryName: 'Honduras' },
  { id: 'hnl_banknote', name: 'Honduran lempira', type: 'banknote', imageUrl: 'https://picsum.photos/seed/hnl_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'HN', countryName: 'Honduras' },
  { id: 'jmd_coin', name: 'Jamaican dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/jmd_coin/600/600', region: 'North America', popularity: 2, countryCode: 'JM', countryName: 'Jamaica' },
  { id: 'jmd_banknote', name: 'Jamaican dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/jmd_banknote/800/400', region: 'North America', popularity: 2, countryCode: 'JM', countryName: 'Jamaica' },
  { id: 'mxn_coin', name: 'Mexican peso', type: 'coin', imageUrl: 'https://picsum.photos/seed/mxn_coin/600/600', region: 'North America', popularity: 1, countryCode: 'MX', countryName: 'Mexico' },
  { id: 'mxn_banknote', name: 'Mexican peso', type: 'banknote', imageUrl: 'https://picsum.photos/seed/mxn_banknote/800/400', region: 'North America', popularity: 1, countryCode: 'MX', countryName: 'Mexico' },
  { id: 'nio_coin', name: 'Nicaraguan córdoba', type: 'coin', imageUrl: 'https://picsum.photos/seed/nio_coin/600/600', region: 'North America', popularity: 3, countryCode: 'NI', countryName: 'Nicaragua' },
  { id: 'nio_banknote', name: 'Nicaraguan córdoba', type: 'banknote', imageUrl: 'https://picsum.photos/seed/nio_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'NI', countryName: 'Nicaragua' },
  { id: 'pab_coin', name: 'Panamanian balboa', type: 'coin', imageUrl: 'https://picsum.photos/seed/pab_coin/600/600', region: 'North America', popularity: 3, countryCode: 'PA', countryName: 'Panama' },
  { id: 'pab_banknote', name: 'Panamanian balboa', type: 'banknote', imageUrl: 'https://picsum.photos/seed/pab_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'PA', countryName: 'Panama' },
  { id: 'ttd_coin', name: 'Trinidad and Tobago dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/ttd_coin/600/600', region: 'North America', popularity: 3, countryCode: 'TT', countryName: 'Trinidad and Tobago' },
  { id: 'ttd_banknote', name: 'Trinidad and Tobago dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ttd_banknote/800/400', region: 'North America', popularity: 3, countryCode: 'TT', countryName: 'Trinidad and Tobago' },
  { id: 'usd_coin', name: 'United States dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/usd_coin/600/600', region: 'North America', popularity: 1, countryCode: 'US', countryName: 'United States' },
  { id: 'usd_banknote', name: 'United States dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/usd_banknote/800/400', region: 'North America', popularity: 1, countryCode: 'US', countryName: 'United States' },

  // Oceania
  { id: 'aud_coin', name: 'Australian dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/aud_coin/600/600', region: 'Oceania', popularity: 1, countryCode: 'AU', countryName: 'Australia' },
  { id: 'aud_banknote', name: 'Australian dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/aud_banknote/800/400', region: 'Oceania', popularity: 1, countryCode: 'AU', countryName: 'Australia' },
  { id: 'xpf_coin', name: 'CFP franc', type: 'coin', imageUrl: 'https://picsum.photos/seed/xpf_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'PF', countryName: 'French Polynesia' },
  { id: 'xpf_banknote', name: 'CFP franc', type: 'banknote', imageUrl: 'https://picsum.photos/seed/xpf_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'PF', countryName: 'French Polynesia' },
  { id: 'ckd_coin', name: 'Cook Islands dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/ckd_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'CK', countryName: 'Cook Islands' },
  { id: 'ckd_banknote', name: 'Cook Islands dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ckd_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'CK', countryName: 'Cook Islands' },
  { id: 'fjd_coin', name: 'Fijian dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/fjd_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'FJ', countryName: 'Fiji' },
  { id: 'fjd_banknote', name: 'Fijian dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/fjd_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'FJ', countryName: 'Fiji' },
  { id: 'kid_coin', name: 'Kiribati dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/kid_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'KI', countryName: 'Kiribati' },
  { id: 'kid_banknote', name: 'Kiribati dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/kid_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'KI', countryName: 'Kiribati' },
  { id: 'nzd_coin', name: 'New Zealand dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/nzd_coin/600/600', region: 'Oceania', popularity: 1, countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'nzd_banknote', name: 'New Zealand dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/nzd_banknote/800/400', region: 'Oceania', popularity: 1, countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'pgk_coin', name: 'Papua New Guinean kina', type: 'coin', imageUrl: 'https://picsum.photos/seed/pgk_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'PG', countryName: 'Papua New Guinea' },
  { id: 'pgk_banknote', name: 'Papua New Guinean kina', type: 'banknote', imageUrl: 'https://picsum.photos/seed/pgk_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'PG', countryName: 'Papua New Guinea' },
  { id: 'wst_coin', name: 'Samoan tālā', type: 'coin', imageUrl: 'https://picsum.photos/seed/wst_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'WS', countryName: 'Samoa' },
  { id: 'wst_banknote', name: 'Samoan tālā', type: 'banknote', imageUrl: 'https://picsum.photos/seed/wst_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'WS', countryName: 'Samoa' },
  { id: 'sbd_coin', name: 'Solomon Islands dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/sbd_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'SB', countryName: 'Solomon Islands' },
  { id: 'sbd_banknote', name: 'Solomon Islands dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/sbd_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'SB', countryName: 'Solomon Islands' },
  { id: 'top_coin', name: 'Tongan paʻanga', type: 'coin', imageUrl: 'https://picsum.photos/seed/top_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'TO', countryName: 'Tonga' },
  { id: 'top_banknote', name: 'Tongan paʻanga', type: 'banknote', imageUrl: 'https://picsum.photos/seed/top_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'TO', countryName: 'Tonga' },
  { id: 'tvd_coin', name: 'Tuvaluan dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/tvd_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'TV', countryName: 'Tuvalu' },
  { id: 'tvd_banknote', name: 'Tuvaluan dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/tvd_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'TV', countryName: 'Tuvalu' },
  { id: 'vuv_coin', name: 'Vanuatu vatu', type: 'coin', imageUrl: 'https://picsum.photos/seed/vuv_coin/600/600', region: 'Oceania', popularity: 3, countryCode: 'VU', countryName: 'Vanuatu' },
  { id: 'vuv_banknote', name: 'Vanuatu vatu', type: 'banknote', imageUrl: 'https://picsum.photos/seed/vuv_banknote/800/400', region: 'Oceania', popularity: 3, countryCode: 'VU', countryName: 'Vanuatu' },

  // South America
  { id: 'ars_coin', name: 'Argentine peso', type: 'coin', imageUrl: 'https://picsum.photos/seed/ars_coin/600/600', region: 'South America', popularity: 2, countryCode: 'AR', countryName: 'Argentina' },
  { id: 'ars_banknote', name: 'Argentine peso', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ars_banknote/800/400', region: 'South America', popularity: 2, countryCode: 'AR', countryName: 'Argentina' },
  { id: 'bob_coin', name: 'Bolivian boliviano', type: 'coin', imageUrl: 'https://picsum.photos/seed/bob_coin/600/600', region: 'South America', popularity: 3, countryCode: 'BO', countryName: 'Bolivia' },
  { id: 'bob_banknote', name: 'Bolivian boliviano', type: 'banknote', imageUrl: 'https://picsum.photos/seed/bob_banknote/800/400', region: 'South America', popularity: 3, countryCode: 'BO', countryName: 'Bolivia' },
  { id: 'brl_coin', name: 'Brazilian real', type: 'coin', imageUrl: 'https://picsum.photos/seed/brl_coin/600/600', region: 'South America', popularity: 1, countryCode: 'BR', countryName: 'Brazil' },
  { id: 'brl_banknote', name: 'Brazilian real', type: 'banknote', imageUrl: 'https://picsum.photos/seed/brl_banknote/800/400', region: 'South America', popularity: 1, countryCode: 'BR', countryName: 'Brazil' },
  { id: 'clp_coin', name: 'Chilean peso', type: 'coin', imageUrl: 'https://picsum.photos/seed/clp_coin/600/600', region: 'South America', popularity: 2, countryCode: 'CL', countryName: 'Chile' },
  { id: 'clp_banknote', name: 'Chilean peso', type: 'banknote', imageUrl: 'https://picsum.photos/seed/clp_banknote/800/400', region: 'South America', popularity: 2, countryCode: 'CL', countryName: 'Chile' },
  { id: 'cop_coin', name: 'Colombian peso', type: 'coin', imageUrl: 'https://picsum.photos/seed/cop_coin/600/600', region: 'South America', popularity: 2, countryCode: 'CO', countryName: 'Colombia' },
  { id: 'cop_banknote', name: 'Colombian peso', type: 'banknote', imageUrl: 'https://picsum.photos/seed/cop_banknote/800/400', region: 'South America', popularity: 2, countryCode: 'CO', countryName: 'Colombia' },
  { id: 'fkp_coin', name: 'Falkland Islands pound', type: 'coin', imageUrl: 'https://picsum.photos/seed/fkp_coin/600/600', region: 'South America', popularity: 3, countryCode: 'FK', countryName: 'Falkland Islands' },
  { id: 'fkp_banknote', name: 'Falkland Islands pound', type: 'banknote', imageUrl: 'https://picsum.photos/seed/fkp_banknote/800/400', region: 'South America', popularity: 3, countryCode: 'FK', countryName: 'Falkland Islands' },
  { id: 'gyd_coin', name: 'Guyanese dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/gyd_coin/600/600', region: 'South America', popularity: 3, countryCode: 'GY', countryName: 'Guyana' },
  { id: 'gyd_banknote', name: 'Guyanese dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/gyd_banknote/800/400', region: 'South America', popularity: 3, countryCode: 'GY', countryName: 'Guyana' },
  { id: 'pyg_coin', name: 'Paraguayan guaraní', type: 'coin', imageUrl: 'https://picsum.photos/seed/pyg_coin/600/600', region: 'South America', popularity: 3, countryCode: 'PY', countryName: 'Paraguay' },
  { id: 'pyg_banknote', name: 'Paraguayan guaraní', type: 'banknote', imageUrl: 'https://picsum.photos/seed/pyg_banknote/800/400', region: 'South America', popularity: 3, countryCode: 'PY', countryName: 'Paraguay' },
  { id: 'pen_coin', name: 'Peruvian sol', type: 'coin', imageUrl: 'https://picsum.photos/seed/pen_coin/600/600', region: 'South America', popularity: 2, countryCode: 'PE', countryName: 'Peru' },
  { id: 'pen_banknote', name: 'Peruvian sol', type: 'banknote', imageUrl: 'https://picsum.photos/seed/pen_banknote/800/400', region: 'South America', popularity: 2, countryCode: 'PE', countryName: 'Peru' },
  { id: 'srd_coin', name: 'Surinamese dollar', type: 'coin', imageUrl: 'https://picsum.photos/seed/srd_coin/600/600', region: 'South America', popularity: 3, countryCode: 'SR', countryName: 'Suriname' },
  { id: 'srd_banknote', name: 'Surinamese dollar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/srd_banknote/800/400', region: 'South America', popularity: 3, countryCode: 'SR', countryName: 'Suriname' },
  { id: 'uyu_coin', name: 'Uruguayan peso', type: 'coin', imageUrl: 'https://picsum.photos/seed/uyu_coin/600/600', region: 'South America', popularity: 3, countryCode: 'UY', countryName: 'Uruguay' },
  { id: 'uyu_banknote', name: 'Uruguayan peso', type: 'banknote', imageUrl: 'https://picsum.photos/seed/uyu_banknote/800/400', region: 'South America', popularity: 3, countryCode: 'UY', countryName: 'Uruguay' },
  { id: 'ves_coin', name: 'Venezuelan sovereign bolívar', type: 'coin', imageUrl: 'https://picsum.photos/seed/ves_coin/600/600', region: 'South America', popularity: 2, countryCode: 'VE', countryName: 'Venezuela' },
  { id: 'ves_banknote', name: 'Venezuelan sovereign bolívar', type: 'banknote', imageUrl: 'https://picsum.photos/seed/ves_banknote/800/400', region: 'South America', popularity: 2, countryCode: 'VE', countryName: 'Venezuela' },
];

export const INITIAL_COINS = 100;
export const DEFAULT_UNLOCKED_CURRENCY_IDS = [
    'eur_coin', 'eur_banknote', 
    'usd_coin', 'usd_banknote', 
    'jpy_coin', 'jpy_banknote', 
    'gbp_coin', 'gbp_banknote', 
    'cad_coin', 'cad_banknote'
];

export const REGION_VIEWBOXES: Record<Region | 'All Regions', string> = {
  'All Regions': '0 0 2000 1001',
  'Africa': '850 350 350 450',
  'Asia': '1050 150 600 500',
  'Europe': '900 150 300 250',
  'North America': '150 100 600 450',
  'South America': '450 550 300 400',
  'Oceania': '1500 550 400 300',
};

export const THEMES: Theme[] = [
  { id: 'emerald_sea', name: 'Emerald Sea', price: 0, colors: { primary: '16 185 129', secondary: '14 165 233', accent: '245 158 11', bgLight: '240 253 250', bgDark: '13 47 43' } },
  { id: 'ruby_sunset', name: 'Ruby Sunset', price: 250, colors: { primary: '197 40 61', secondary: '233 114 76', accent: '255 200 87', bgLight: '254 242 242', bgDark: '68 25 25' } },
  { id: 'amethyst_sky', name: 'Amethyst Sky', price: 250, colors: { primary: '147 51 234', secondary: '234 179 8', accent: '244 63 94', bgLight: '245 243 255', bgDark: '28 12 59' } },
  { id: 'mystic_golden', name: 'Mystic Golden', price: 500, colors: { primary: '202 203 197', secondary: '230 175 46', accent: '25 23 22', bgLight: '248 250 252', bgDark: '42 38 28' } },
];

export const CURRENCY_PACKS: CurrencyPack[] = [
  { 
    id: 'pack_europe', 
    name: 'Europe Pack', 
    description: 'Unlock 14 items from currencies like the Franc, Krona, and Ruble.', 
    price: 700, 
    currencyIds: [
        'chf_coin', 'chf_banknote', 
        'sek_coin', 'sek_banknote', 
        'nok_coin', 'nok_banknote', 
        'rub_coin', 'rub_banknote', 
        'pln_coin', 'pln_banknote', 
        'dkk_coin', 'dkk_banknote', 
        'huf_coin', 'huf_banknote'
    ] 
  },
  { 
    id: 'pack_asia', 
    name: 'Asia Pack', 
    description: 'Discover 14 items from the Yuan, Rupee, Won, and more.', 
    price: 700, 
    currencyIds: [
        'cny_coin', 'cny_banknote',
        'inr_coin', 'inr_banknote',
        'krw_coin', 'krw_banknote',
        'sgd_coin', 'sgd_banknote',
        'thb_coin', 'thb_banknote',
        'myr_coin', 'myr_banknote',
        'idr_coin', 'idr_banknote'
    ] 
  },
  { 
    id: 'pack_americas', 
    name: 'Americas Pack', 
    description: 'Expand your collection with 12 items from the Americas.', 
    price: 600, 
    currencyIds: [
        'brl_coin', 'brl_banknote',
        'mxn_coin', 'mxn_banknote',
        'ars_coin', 'ars_banknote',
        'clp_coin', 'clp_banknote',
        'cop_coin', 'cop_banknote',
        'pen_coin', 'pen_banknote'
    ]
  },
  { 
    id: 'pack_africa_oceania', 
    name: 'Africa & Oceania Pack', 
    description: 'Explore 14 items from Africa and down under.', 
    price: 700, 
    currencyIds: [
        'aud_coin', 'aud_banknote',
        'nzd_coin', 'nzd_banknote',
        'zar_coin', 'zar_banknote',
        'egp_coin', 'egp_banknote',
        'ngn_coin', 'ngn_banknote',
        'kes_coin', 'kes_banknote',
        'fjd_coin', 'fjd_banknote'
    ]
  },
  {
    id: 'pack_africa_explorers',
    name: 'African Explorers',
    description: 'Journey through Africa with 10 items from the Dinar to the Pula.',
    price: 800,
    currencyIds: [
        'dzd_coin', 'dzd_banknote',
        'ghs_coin', 'ghs_banknote',
        'mad_coin', 'mad_banknote',
        'etb_coin', 'etb_banknote',
        'bwp_coin', 'bwp_banknote'
    ]
  },
  {
    id: 'pack_asia_treasures',
    name: 'Asian Treasures',
    description: 'Uncover 10 hidden gems from Asia, from the Lira to the Đồng.',
    price: 800,
    currencyIds: [
        'ils_coin', 'ils_banknote',
        'aed_coin', 'aed_banknote',
        'try_coin', 'try_banknote',
        'php_coin', 'php_banknote',
        'vnd_coin', 'vnd_banknote'
    ]
  },
  {
    id: 'pack_south_america_wonders',
    name: 'South American Wonders',
    description: 'Discover the vibrant economies of South America with these 10 items.',
    price: 800,
    currencyIds: [
        'uyu_coin', 'uyu_banknote',
        'pyg_coin', 'pyg_banknote',
        'bob_coin', 'bob_banknote',
        'gyd_coin', 'gyd_banknote',
        'srd_coin', 'srd_banknote'
    ]
  }
];